version: "3.7"
services:
    app:
        build:
            args:
                user: www-data
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: ropem_app
        container_name: ropem_app_container
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        environment:
            # Laravel environment variables
            APP_NAME: ${APP_NAME}
            APP_ENV: ${APP_ENV}
            APP_KEY: ${APP_KEY}
            APP_DEBUG: ${APP_DEBUG}
            APP_URL: ${APP_URL}
            LOG_CHANNEL: ${LOG_CHANNEL}
            LOG_DEPRECATIONS_CHANNEL: ${LOG_DEPRECATIONS_CHANNEL}
            LOG_LEVEL: ${LOG_LEVEL}
            DB_CONNECTION: ${DB_CONNECTION}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            BROADCAST_DRIVER: ${BROADCAST_DRIVER}
            CACHE_DRIVER: ${CACHE_DRIVER}
            FILESYSTEM_DRIVER: ${FILESYSTEM_DRIVER}
            QUEUE_CONNECTION: ${QUEUE_CONNECTION}
            SESSION_DRIVER: ${SESSION_DRIVER}
            SESSION_LIFETIME: ${SESSION_LIFETIME}
            MEMCACHED_HOST: ${MEMCACHED_HOST}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            REDIS_PORT: ${REDIS_PORT}
            MAIL_MAILER: ${MAIL_MAILER}
            MAIL_HOST: ${MAIL_HOST}
            MAIL_PORT: ${MAIL_PORT}
            MAIL_USERNAME: ${MAIL_USERNAME}
            MAIL_PASSWORD: ${MAIL_PASSWORD}
            MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
            MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
            MAIL_FROM_NAME: ${MAIL_FROM_NAME}
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
            AWS_BUCKET: ${AWS_BUCKET}
            AWS_USE_PATH_STYLE_ENDPOINT: ${AWS_USE_PATH_STYLE_ENDPOINT}
            PUSHER_APP_ID: ${PUSHER_APP_ID}
            PUSHER_APP_KEY: ${PUSHER_APP_KEY}
            PUSHER_APP_SECRET: ${PUSHER_APP_SECRET}
            PUSHER_APP_CLUSTER: ${PUSHER_APP_CLUSTER}
            MIX_PUSHER_APP_KEY: ${MIX_PUSHER_APP_KEY}
            MIX_PUSHER_APP_CLUSTER: ${MIX_PUSHER_APP_CLUSTER}
            APP_VERSION: ${APP_VERSION}
            JWT_SECRET: ${JWT_SECRET}
        networks:
            - ropem_network

    db:
        image: mysql:8.0
        container_name: ropem_db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ropem
            MYSQL_ROOT_PASSWORD: AZ4JlWlQGREG5
            MYSQL_PASSWORD: mysql
            MYSQL_USER: mysql
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
        networks:
            - ropem_network

    nginx:
        image: nginx:alpine
        container_name: ropem_nginx_container
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./nginx:/etc/nginx/conf.d/
        networks:
            - ropem_network

    redis:
        image: redis:latest
        container_name: ropem_redis_container
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - ropem_network

    memcached:
        image: memcached:latest
        container_name: ropem_memcached_container
        restart: unless-stopped
        ports:
            - "11211:11211"
        networks:
            - ropem_network

networks:
    ropem_network:
        driver: bridge
